/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-secondary-container": "#694d0c",
          "on-secondary-fixed": "#543b00",
          "on-primary-fixed": "#3f3f3f",
          "surface-bright": "#fcf9f8",
          "tertiary-dim": "#525450",
          "surface-container-highest": "#e4e2e2",
          "on-surface": "#323233",
          "primary-container": "#e2e2e2",
          "outline-variant": "#b2b2b1",
          "on-primary": "#f8f8f8",
          "error": "#9f403d",
          "tertiary": "#5e605c",
          "error-dim": "#4e0309",
          "surface-container": "#f0eded",
          "secondary-fixed": "#ffdea5",
          "on-background": "#323233",
          "primary-dim": "#525252",
          "secondary-container": "#ffdea5",
          "on-error-container": "#752121",
          "on-primary-fixed-variant": "#5b5b5b",
          "secondary-fixed-dim": "#f8cf83",
          "on-error": "#fff7f6",
          "surface-container-low": "#f6f3f2",
          "surface-variant": "#e4e2e2",
          "surface": "#fcf9f8",
          "primary-fixed": "#e2e2e2",
          "on-tertiary-fixed": "#484a47",
          "on-secondary": "#fff8f1",
          "tertiary-fixed": "#f4f4ef",
          "inverse-on-surface": "#9e9c9c",
          "surface-container-high": "#eae8e7",
          "on-tertiary-container": "#5b5c59",
          "primary-fixed-dim": "#d4d4d4",
          "secondary-dim": "#6b4e0e",
          "inverse-primary": "#ffffff",
          "on-surface-variant": "#5f5f5f",
          "tertiary-container": "#f4f4ef",
          "background": "#fcf9f8",
          "secondary": "#785a1a",
          "inverse-surface": "#0e0e0e",
          "surface-tint": "#5e5e5e",
          "tertiary-fixed-dim": "#e5e6e1",
          "primary": "#5e5e5e",
          "surface-dim": "#dbdad9",
          "on-tertiary-fixed-variant": "#656763",
          "on-primary-container": "#525252",
          "surface-container-lowest": "#ffffff",
          "error-container": "#fe8983",
          "outline": "#7b7b7a",
          "on-tertiary": "#f9f9f4",
          "on-secondary-fixed-variant": "#745716"
      },
      "borderRadius": {
          "DEFAULT": "0px",
          "lg": "0px",
          "xl": "0px",
          "full": "9999px"
      },
      "fontFamily": {
          "headline": ["Newsreader", "serif"],
          "display": ["Newsreader", "serif"],
          "body": ["Manrope", "sans-serif"],
          "label": ["Manrope", "sans-serif"],
          "sans": ["Manrope", "sans-serif"],
          "serif": ["Newsreader", "serif"]
      }
    },
  },
  plugins: [],
}
